const ActionTypes = {
  START_GET_EMP: 'START_GET_EMP',
  DONE_GET_EMP: 'DONE_GET_EMP',
  STOP_GET_EMP: 'STOP_GET_EMP',
  START_POST_SURVEY: 'START_POS_SURVEY',
  DONE_POST_SURVEY: 'DONE_POST_SURVEY',
  STOP_POST_SURVEY: 'STOP_POST_SURVEY',
};

export default ActionTypes;
